SecurityCache: "<%= ENV['HOME'] %>/jupyter/workstation/pyTrading/data/security.csv"
MarketDataManager: 
  Indicator: 
    - 
      Id: CCI_18
      SecId: HSIY0
      Type: CCI
      Parameters: 18
    - 
      Id: DMI_14
      SecId: IF0001
      Type: DMI
      Parameters:
        DI Length: 14
        ADX Smooth: 14
  MarketData: 
    - 
      File: "<%= ENV['HOME'] %>/jupyter/workstation/pyTrading/data/HSIY0 history.csv"
      SecId: HSIY0
      Start: 100
    - 
      File: "<%= ENV['HOME'] %>/jupyter/workstation/pyTrading/data/IF0001 history.csv"
      SecId: IF0001
TradeManager: 
PositionManager: 
  value: 
    init_cash: 2000000
    isMargin: 1
RiskManager: 
  type: FixPctRiskManager
  value: 
    MaxCapitalPercentage: 50
    TotalRiskPercentage: 2
OrderManager:
  type: Simulator
StrategyManager:
DataCollector:
  base_dir: "<%= ENV['HOME'] %>/jupyter/workstation/pyTrading/output"
